name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  change_app_package_name: ^1.0.0
  cloud_firestore: ^2.5.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.6.1
  google_sign_in: ^5.0.7
  image_cropper: ^1.4.1
  image_picker: ^0.8.3+3
  lottie: ^1.1.0
  my_fatoorah: ^3.0.6
  path: ^1.8.0
  provider: ^5.0.0
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  timelines: ^0.1.0
  translator: ^0.1.7
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adpative_icon_background: "#00C569"
  adpative_icon_foreground: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/json/
